version: '3.8'

services:
  resource-monitor:
    image: jeffmittens/resourcemonitor:latest
    container_name: resource-monitor-gpu
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
    volumes:
      # Mount host configuration file
      - /etc/resourcemonitor/config:/etc/resourcemonitor/config:ro
      # Mount logs to host for persistence
      - ./logs:/app/logs
      # Mount host /proc for accurate system metrics
      - /proc:/host/proc:ro
      # Mount host /sys for system information
      - /sys:/host/sys:ro
    privileged: false
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - resource-monitor-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  resource-monitor-net:
    driver: bridge
