version = 0.1
[default]
[default.global.parameters]
stack_name = "resource-monitor-s3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "BucketName=resource-monitor-data",
    "AvailabilityZone=us-east-2a"
]

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
